### ISSUE TITLE
java.lang.IllegalStateException: Timer was canceled

### ISSUE THREAD

**Issue by farble1670** [openhab/jmdns#35]
```
java.lang.IllegalStateException: Timer was canceled
at java.util.Timer.scheduleImpl(Timer.java:561)
at java.util.Timer.schedule(Timer.java:459)
at javax.jmdns.impl.DNSTaskStarter$DNSTaskStarterImpl$StarterTimer.schedule(DNSTaskStarter.java:219)
at javax.jmdns.impl.tasks.Responder.start(Responder.java:101)
at javax.jmdns.impl.DNSTaskStarter$DNSTaskStarterImpl.startResponder(DNSTaskStarter.java:395)
at javax.jmdns.impl.JmDNSImpl.startResponder(JmDNSImpl.java:1671)
at javax.jmdns.impl.JmDNSImpl.handleQuery(JmDNSImpl.java:1461)
at javax.jmdns.impl.SocketListener.run(SocketListener.java:59)
```

i do not know the circumstances that reproduce this, but we see it in the wild quite often.

**Comment by Ravi1988** [comment]
Fatal Exception: java.lang.IllegalStateException: Timer already cancelled.
       at java.util.Timer.sched(Timer.java:404)
       at java.util.Timer.schedule(Timer.java:200)
       at javax.jmdns.impl.tasks.Responder.start(SourceFile:91)
       at javax.jmdns.impl.DNSTaskStarter$DNSTaskStarterImpl.startResponder(SourceFile:272)
       at javax.jmdns.impl.JmDNSImpl.startResponder(SourceFile:1656)
       at javax.jmdns.impl.JmDNSImpl.handleQuery(SourceFile:1457)
       at javax.jmdns.impl.SocketListener.run(SourceFile:56)

Facing same error. @farble1670 did you solve this by any chance?

**Comment by ViToni** [comment]
Might not necessarily be an error.
If one gets a query and there is someone else in the network providing the same answer as we would, the response preparation could be canceled...

**Comment by farble1670** [comment]
> Might not necessarily be an error.

Then it probably shouldn't throw am unchecked, runtime exception that crashes the application.

**Comment by ViToni** [comment]
> > Might not necessarily be an error.
> 
> Then it probably shouldn't throw an unchecked, runtime exception that crashes the application.

This behavior indeed seems to be a bug.

**Comment by bubbleguuum** [comment]
Still happening (seen on 3.5.6), although quite rare:

```
java.lang.IllegalStateException: Timer already cancelled.
at java.util.Timer.sched(Timer.java)
at java.util.Timer.schedule(Timer.java)
at javax.jmdns.impl.DNSTaskStarter$DNSTaskStarterImpl$StarterTimer.schedule(DNSTaskStarter.java:219)
at javax.jmdns.impl.tasks.Responder.start(Responder.java:98)
at javax.jmdns.impl.DNSTaskStarter$DNSTaskStarterImpl.startResponder(DNSTaskStarter.java:395)
at javax.jmdns.impl.JmDNSImpl.startResponder(JmDNSImpl.java:1770)
at javax.jmdns.impl.JmDNSImpl.handleQuery(JmDNSImpl.java:1560)
at javax.jmdns.impl.SocketListener.run(SocketListener.java:75)
```
